export const MODEL_NAME = 'claude-sonnet-4-20250514';
export const MAX_RESPONSE_TOKENS = 4096;
export const TARGET_MESSAGE_TOKENS = 80000;
export const SYSTEM_PROMPT_BUFFER = 4000;
export const AVAILABLE_FOR_MESSAGES = TARGET_MESSAGE_TOKENS - SYSTEM_PROMPT_BUFFER - MAX_RESPONSE_TOKENS;
